// Default German starter decks and cards

export const DEFAULT_DECKS = [
  { id: 'deck-basics', name: 'Basics & Greetings', description: 'Essential German phrases and greetings', color: '#4f46e5' },
  { id: 'deck-numbers', name: 'Numbers', description: 'German numbers 1–20 and beyond', color: '#0891b2' },
  { id: 'deck-colors', name: 'Colors', description: 'German color vocabulary', color: '#059669' },
  { id: 'deck-common', name: 'Common Words', description: '50 most common German words', color: '#d97706' },
];

export const DEFAULT_CARDS = [
  // Basics & Greetings
  { id: 'c1', deckId: 'deck-basics', front: 'Hallo', back: 'Hello', hint: 'Informal greeting' },
  { id: 'c2', deckId: 'deck-basics', front: 'Guten Morgen', back: 'Good morning', hint: '' },
  { id: 'c3', deckId: 'deck-basics', front: 'Guten Tag', back: 'Good day / Good afternoon', hint: 'Formal greeting' },
  { id: 'c4', deckId: 'deck-basics', front: 'Guten Abend', back: 'Good evening', hint: '' },
  { id: 'c5', deckId: 'deck-basics', front: 'Gute Nacht', back: 'Good night', hint: '' },
  { id: 'c6', deckId: 'deck-basics', front: 'Auf Wiedersehen', back: 'Goodbye', hint: 'Formal farewell' },
  { id: 'c7', deckId: 'deck-basics', front: 'Tschüss', back: 'Bye', hint: 'Informal farewell' },
  { id: 'c8', deckId: 'deck-basics', front: 'Bitte', back: 'Please / You\'re welcome', hint: 'Context dependent' },
  { id: 'c9', deckId: 'deck-basics', front: 'Danke', back: 'Thank you', hint: '' },
  { id: 'c10', deckId: 'deck-basics', front: 'Danke schön', back: 'Thank you very much', hint: '' },
  { id: 'c11', deckId: 'deck-basics', front: 'Entschuldigung', back: 'Excuse me / Sorry', hint: '' },
  { id: 'c12', deckId: 'deck-basics', front: 'Ja', back: 'Yes', hint: '' },
  { id: 'c13', deckId: 'deck-basics', front: 'Nein', back: 'No', hint: '' },
  { id: 'c14', deckId: 'deck-basics', front: 'Wie heißen Sie?', back: 'What is your name? (formal)', hint: '' },
  { id: 'c15', deckId: 'deck-basics', front: 'Ich heiße...', back: 'My name is...', hint: '' },
  { id: 'c16', deckId: 'deck-basics', front: 'Wie geht es Ihnen?', back: 'How are you? (formal)', hint: '' },
  { id: 'c17', deckId: 'deck-basics', front: 'Mir geht es gut', back: 'I am doing well', hint: '' },
  { id: 'c18', deckId: 'deck-basics', front: 'Ich verstehe nicht', back: 'I don\'t understand', hint: '' },
  { id: 'c19', deckId: 'deck-basics', front: 'Sprechen Sie Englisch?', back: 'Do you speak English?', hint: 'Formal' },
  { id: 'c20', deckId: 'deck-basics', front: 'Wo ist die Toilette?', back: 'Where is the toilet?', hint: 'Very useful!' },

  // Numbers
  { id: 'n1', deckId: 'deck-numbers', front: 'eins', back: '1', hint: '' },
  { id: 'n2', deckId: 'deck-numbers', front: 'zwei', back: '2', hint: '' },
  { id: 'n3', deckId: 'deck-numbers', front: 'drei', back: '3', hint: '' },
  { id: 'n4', deckId: 'deck-numbers', front: 'vier', back: '4', hint: '' },
  { id: 'n5', deckId: 'deck-numbers', front: 'fünf', back: '5', hint: '' },
  { id: 'n6', deckId: 'deck-numbers', front: 'sechs', back: '6', hint: '' },
  { id: 'n7', deckId: 'deck-numbers', front: 'sieben', back: '7', hint: '' },
  { id: 'n8', deckId: 'deck-numbers', front: 'acht', back: '8', hint: '' },
  { id: 'n9', deckId: 'deck-numbers', front: 'neun', back: '9', hint: '' },
  { id: 'n10', deckId: 'deck-numbers', front: 'zehn', back: '10', hint: '' },
  { id: 'n11', deckId: 'deck-numbers', front: 'elf', back: '11', hint: '' },
  { id: 'n12', deckId: 'deck-numbers', front: 'zwölf', back: '12', hint: '' },
  { id: 'n13', deckId: 'deck-numbers', front: 'dreizehn', back: '13', hint: '' },
  { id: 'n14', deckId: 'deck-numbers', front: 'vierzehn', back: '14', hint: '' },
  { id: 'n15', deckId: 'deck-numbers', front: 'fünfzehn', back: '15', hint: '' },
  { id: 'n16', deckId: 'deck-numbers', front: 'zwanzig', back: '20', hint: '' },
  { id: 'n17', deckId: 'deck-numbers', front: 'dreißig', back: '30', hint: '' },
  { id: 'n18', deckId: 'deck-numbers', front: 'hundert', back: '100', hint: '' },
  { id: 'n19', deckId: 'deck-numbers', front: 'tausend', back: '1000', hint: '' },

  // Colors
  { id: 'col1', deckId: 'deck-colors', front: 'rot', back: 'red', hint: '' },
  { id: 'col2', deckId: 'deck-colors', front: 'blau', back: 'blue', hint: '' },
  { id: 'col3', deckId: 'deck-colors', front: 'grün', back: 'green', hint: '' },
  { id: 'col4', deckId: 'deck-colors', front: 'gelb', back: 'yellow', hint: '' },
  { id: 'col5', deckId: 'deck-colors', front: 'schwarz', back: 'black', hint: '' },
  { id: 'col6', deckId: 'deck-colors', front: 'weiß', back: 'white', hint: '' },
  { id: 'col7', deckId: 'deck-colors', front: 'grau', back: 'grey', hint: '' },
  { id: 'col8', deckId: 'deck-colors', front: 'orange', back: 'orange', hint: 'Same as English!' },
  { id: 'col9', deckId: 'deck-colors', front: 'rosa', back: 'pink', hint: '' },
  { id: 'col10', deckId: 'deck-colors', front: 'lila', back: 'purple', hint: '' },
  { id: 'col11', deckId: 'deck-colors', front: 'braun', back: 'brown', hint: '' },

  // Common Words
  { id: 'w1', deckId: 'deck-common', front: 'der Mann', back: 'the man', hint: 'der = masculine article' },
  { id: 'w2', deckId: 'deck-common', front: 'die Frau', back: 'the woman / wife', hint: 'die = feminine article' },
  { id: 'w3', deckId: 'deck-common', front: 'das Kind', back: 'the child', hint: 'das = neuter article' },
  { id: 'w4', deckId: 'deck-common', front: 'das Haus', back: 'the house', hint: '' },
  { id: 'w5', deckId: 'deck-common', front: 'das Wasser', back: 'the water', hint: '' },
  { id: 'w6', deckId: 'deck-common', front: 'das Essen', back: 'the food / meal', hint: '' },
  { id: 'w7', deckId: 'deck-common', front: 'die Zeit', back: 'the time', hint: '' },
  { id: 'w8', deckId: 'deck-common', front: 'der Tag', back: 'the day', hint: '' },
  { id: 'w9', deckId: 'deck-common', front: 'die Nacht', back: 'the night', hint: '' },
  { id: 'w10', deckId: 'deck-common', front: 'gut', back: 'good', hint: '' },
  { id: 'w11', deckId: 'deck-common', front: 'schlecht', back: 'bad', hint: '' },
  { id: 'w12', deckId: 'deck-common', front: 'groß', back: 'big / tall', hint: '' },
  { id: 'w13', deckId: 'deck-common', front: 'klein', back: 'small / short', hint: '' },
  { id: 'w14', deckId: 'deck-common', front: 'ich', back: 'I', hint: 'Personal pronoun' },
  { id: 'w15', deckId: 'deck-common', front: 'du', back: 'you (informal)', hint: '' },
  { id: 'w16', deckId: 'deck-common', front: 'er / sie / es', back: 'he / she / it', hint: '' },
  { id: 'w17', deckId: 'deck-common', front: 'wir', back: 'we', hint: '' },
  { id: 'w18', deckId: 'deck-common', front: 'sein', back: 'to be', hint: 'Infinitive' },
  { id: 'w19', deckId: 'deck-common', front: 'haben', back: 'to have', hint: 'Infinitive' },
  { id: 'w20', deckId: 'deck-common', front: 'machen', back: 'to do / to make', hint: '' },
  { id: 'w21', deckId: 'deck-common', front: 'gehen', back: 'to go', hint: '' },
  { id: 'w22', deckId: 'deck-common', front: 'kommen', back: 'to come', hint: '' },
  { id: 'w23', deckId: 'deck-common', front: 'sehen', back: 'to see', hint: '' },
  { id: 'w24', deckId: 'deck-common', front: 'wissen', back: 'to know (a fact)', hint: '' },
  { id: 'w25', deckId: 'deck-common', front: 'mögen', back: 'to like', hint: '' },
];
